pipeline {
    agent any
    environment {
                PROJECT_ID = 'seraphic-bliss-356414'
                CLUSTER_NAME = 'cluster001'
                LOCATION = 'us-central1-c'
                CREDENTIALS_ID = 'kubernetes'
    }
    
    stages {    
        stage('Deploy to K8s') {
            steps{
                echo "Deployment started ..."
                sh 'ls -ltr'
                sh 'pwd'}
                step([$class: 'KubernetesEngineBuilder', \
                  projectId: env.PROJECT_ID, \
                  clusterName: env.CLUSTER_NAME, \
                  location: env.LOCATION, \
                  manifestPattern: 'nodejs.yaml', \
                  credentialsId: env.CREDENTIALS_ID, \
                  verifyDeployments: true])
                }
            }
        }    
}
