pipeline {
    agent any
    environment {
        PROJECT_ID = 'seraphic-bliss-356414'
        CLUSTER_NAME = 'cluster001'
        LOCATION = 'us-central1-c'
        CREDENTIALS_ID = 'My First Project'
    }
    stages {
        podTemplate(inheritFrom: 'default'){
            node(POD_LABEL){
                stage('Deploy to K8s') {
                    steps{
                        withKubeConfig([credentialsId: 'cluster001',
                            serverUrl: '35.225.244.101',
                            clusterName: 'cluster001'
                            ]) {
                            sh 'kubectl get pods'
                        }
                    }
                }
            }
        }
    }
}