pipeline {
    agent any
    environment {
        PROJECT_ID = 'seraphic-bliss-356414'
        CLUSTER_NAME = 'cluster001'
        LOCATION = 'us-central1-c'
        CREDENTIALS_ID = 'My First Project'
    }
    stages {
        stage('Deploy to GKE') {
            steps{
                sh '''#!/bin/bash
                        wget https://raw.githubusercontent.com/LisandroLuna/devopsChallenge/main/apps/prueba/namespace.yaml
                '''
                step([
                $class: 'KubernetesEngineBuilder',
                projectId: env.PROJECT_ID,
                clusterName: env.CLUSTER_NAME,
                location: env.LOCATION,
                manifestPattern: 'namespace.yaml',
                credentialsId: env.CREDENTIALS_ID,
                verifyDeployments: true])
            }
        }
    }
}